Repository asd0236/3NT_Delivery_Shop_Team_Project, pull requests merged in 2024-08, with the labels that each got.

#22 category 도메인 기본 기능 구현 #9
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/CategoryDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/Category.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/CategoryRepository.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/helper/RepositoryHelper.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/helper/ServiceErrorHelper.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/CategoryService.java
Labels: implementation

#23 Docs: .gitIgnore 설정 추가
  .gitIgnore
Labels: bug

#25 #11 user 도메인 기본 기능 구현
  com.3NT.deliveryShop/.gradle/8.8/checksums/checksums.lock
  com.3NT.deliveryShop/.gradle/8.8/executionHistory/executionHistory.lock
  com.3NT.deliveryShop/.gradle/8.8/fileHashes/fileHashes.bin
  com.3NT.deliveryShop/.gradle/8.8/fileHashes/fileHashes.lock
  com.3NT.deliveryShop/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  com.3NT.deliveryShop/build.gradle
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/config/WebSecurityConfig.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/UserController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/UserDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/Timestamped.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/User.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/UserRoleEnum.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/UserRepository.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/security/JwtAuthenticationFilter.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/security/JwtAuthorizationFilter.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/security/UserDetailsImpl.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/security/UserDetailsServiceImpl.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/UserService.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/util/JwtUtil.java
  com.3NT.deliveryShop/src/main/resources/application.properties
Labels: implementation

#31 Restaurant 도메인 기본 기능 구현 #7
  com.3NT.deliveryShop/build.gradle
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/RestaurantController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/RestaurantDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/Restaurant.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/Timestamped.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/UserRoleEnum.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/RestaurantRepository.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/custom/RestaurantRepositoryCustom.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/helper/RepositoryHelper.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/implementaion/RestaurantRepositoryImpl.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/querydsl/PagingUtil.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/querydsl/QueryDslConfig.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/searchcondition/RestaurantSearchCondition.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/CategoryService.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/RestaurantService.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/authorizer/AbstractAuthorizer.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/authorizer/AuthenticationInspector.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/authorizer/RestaurantAuthorizer.java
Labels: implementation

#32 27 user 수정 관련 버그
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/config/WebSecurityConfig.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/UserController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/UserDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/UserRepository.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/helper/RepositoryHelper.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/security/JwtAuthenticationFilter.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/security/JwtAuthorizationFilter.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/security/UserDetailsImpl.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/security/UserDetailsServiceImpl.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/UserService.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/util/JwtUtil.java
Labels: bug

#35 fix: Restaurant 도메인 관련 잘못된 필드 및 값 수정
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/RestaurantRepository.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/RestaurantService.java
Labels: bug

#36 fix: Category, Restaurant 도메인의 잘못된 키값 형태 수정
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/RestaurantController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/CategoryRepository.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/helper/RepositoryHelper.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/CategoryService.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/RestaurantService.java
Labels: bug

#38 Feature/12 order 도메인 기본 기능 구현
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/DeliveryShopApplication.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/config/JpaAuditConfig.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/OrderController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/DeliveryInfoDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/OrderDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/OrderItemDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/PaymentInfoDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/Order.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/OrderStatus.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/Payment.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/OrderRepository.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/OrderService.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/util/UserAuditorAware.java
Labels: implementation

#40 Feature/#8 product 도메인 기본 기능 구현
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/ProductController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/ProductDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/Product.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/ProductRepository.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/custom/ProductRepositoryCustom.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/helper/RepositoryHelper.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/implementaion/ProductRepositoryImpl.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/searchcondition/ProductSearchCondition.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/ProductService.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/RestaurantService.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/authorizer/ProductAuthorizer.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/authorizer/RestaurantAuthorizer.java
Labels: implementation, refactor

#44 refactor: UUID 생성 어노테이션 교체
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/Category.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/DeliveryAddress.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/DeliveryInfo.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/Order.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/OrderProduct.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/Payment.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/Product.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/Restaurant.java
Labels: refactor

#45 Feature/18 delivery 도메인 기본 기능
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/UserAddressController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/DeliveryAddressDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/DeliveryAddress.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/DeliveryAddressRepository.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/AddressService.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/OrderService.java
Labels: implementation

#46 fix: AuthInspector의 ADMIN ROLE 의 잘못된 String 값 입력 수정
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/authorizer/AuthenticationInspector.java
Labels: bug

#48 fix: Restaurant update 및 softDelete 관련 버그 수정
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/RestaurantController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/RestaurantService.java
Labels: bug

#49 fix: ProductDto.Result 생성시 필드 누락 및 Put 기능시 특정 필드 유실 문제 수정
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/ProductDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/ProductService.java
Labels: bug

#51 Fix: User Soft Delete 버그 수정
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/security/UserDetailsServiceImpl.java
Labels: bug

#52 fix: softDeleted 가 된 Category, Restaurant, Product가 조회 가능하던 문제 수정
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/helper/RepositoryHelper.java
Labels: bug

#53 Feature/12 order 도메인 기본 기능 구현
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/OrderController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/OrderDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/OrderProductDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/Order.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/OrderProduct.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/OrderProductRepository.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/OrderService.java
Labels: implementation

#56 fix: restaurant soft delete 상태가 category 와 product 에게 전파되지 않는 오류
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/CategoryRepository.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/ProductRepository.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/RestaurantService.java
Labels: bug, implementation
