Repository asd0236/3NT_Delivery_Shop_Team_Project, pull requests merged in 2024-09, with the labels that each got.

#60 Feature/58 proejct deploy
  com.3NT.deliveryShop/Dockerfile
  com.3NT.deliveryShop/build.gradle
Labels: Deploy

#63 S3 를 이용한 이미지 업로드 구현 및 Product 에 대한 해당 기능 적용
  com.3NT.deliveryShop/build.gradle
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/config/AmazonS3Config.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/ProductController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/AmazonS3FileDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/ProductDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/ProductImg.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/UploadFile.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/ProductImgRepository.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/AmazonS3Service.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/ProductImgService.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/ProductService.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/authorizer/ProductAuthorizer.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/authorizer/RestaurantAuthorizer.java
Labels: implementation

#64 57 백오피스 기능 개발
  com.3NT.deliveryShop/build.gradle
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/config/WebSecurityConfig.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/AdminController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/AuthController.java
  com.3NT.deliveryShop/src/main/resources/static/css/styles.css
  com.3NT.deliveryShop/src/main/resources/templates/login.html
  com.3NT.deliveryShop/src/main/resources/templates/main.html
  com.3NT.deliveryShop/src/main/resources/templates/orders.html
  com.3NT.deliveryShop/src/main/resources/templates/payments.html
  com.3NT.deliveryShop/src/main/resources/templates/products.html
  com.3NT.deliveryShop/src/main/resources/templates/restaurants.html
  com.3NT.deliveryShop/src/main/resources/templates/users.html
Labels: implementation

#65 Feature/61 회원 정보 캐시 기능 추가
  com.3NT.deliveryShop/build.gradle
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/config/RedisConfig.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/Timestamped.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/User.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/UserRoleEnum.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/security/UserDetailsServiceImpl.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/UserService.java
Labels: implementation

#67 Swagger UI 설정 및 적용 완료
  com.3NT.deliveryShop/build.gradle
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/config/SwaggerConfig.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/config/WebSecurityConfig.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/AiChatController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/OrderController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/PaymentController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/ProductController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/RestaurantController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/UserAddressController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/UserController.java
Labels: implementation

#70 Feature/Restaurant에서 사용할 이미지 업로드 기능 추가
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/ProductController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/RestaurantController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/AmazonS3FileDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/RestaurantImg.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/entity/UploadFile.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/ProductImgRepository.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/repository/RestaurantImgRepository.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/AmazonS3Service.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/ProductImgService.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/RestaurantImgService.java
Labels: implementation

#73 Docs/공지사항 및 신고 접수에 swagger 적용
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/AiChatController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/AnswerController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/NoticeController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/OrderController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/PaymentController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/ProductController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/ReportController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/RestaurantController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/UserAddressController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/UserController.java
Labels: documentation, refactor

#75 예외 처리 및 응답 공통화
  com.3NT.deliveryShop/build.gradle
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/common/codes/ErrorCode.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/common/codes/SuccessCode.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/common/exception/CustomException.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/common/exception/GlobalExceptionHandler.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/common/response/ErrorResponse.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/common/response/ResultResponse.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/OrderController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/UserAddressController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/AddressService.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/service/OrderService.java
Labels: implementation

#76 배포 자동화
  .github/workflows/deploy.yml
Labels: Deploy

#78 feat: 누락된 응답 공통화 추가
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/common/response/ResultResponse.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/AiChatController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/AnswerController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/NoticeController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/PaymentController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/ProductController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/ReportController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/RestaurantController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/UserController.java
Labels: refactor

#80 refactor: Controller validation 처리
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/AiChatController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/AnswerController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/NoticeController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/OrderController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/PaymentController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/ProductController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/ReportController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/RestaurantController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/UserAddressController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/controller/UserController.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/AiChatDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/AnswerDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/DeliveryAddressDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/NoticeDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/OrderDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/OrderProductDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/PaymentDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/ProductDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/ReportDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/RestaurantDto.java
  com.3NT.deliveryShop/src/main/java/com/_NT/deliveryShop/domain/dto/UserDto.java
Labels: enhancement, refactor
